:showtitle:
:toc: left
:icons: font

= Hayden's CKAN Repository

My CKAN repo for mods I wish were already in the official repo.

== Installation

.With the CKAN GUI (recommended)
[%collapsible]
====
1. Open CKAN, go to Settings -> CKAN Settings.
2. Under "Metadata Repositories", click "New".
3. In the "Name" field, type "HaydensCKAN".
4. In the "URL" field, type `https://github.com/hbjydev/ckan/archive/main.tar.gz`.
5. Click "Add".
6. Close the CKAN settings window.

Your CKAN repository data should now refresh, and the mods I have netkan
configs for will now appear in the available mods list.
====

.With the CKAN CLI
[%collapsible]
====
To add this repository to your CKAN install using the command-line, run the
following:

[source,bash]
----
ckan repo add hbjydev https://github.com/hbjydev/ckan/archive/main.tar.gz
----
====

== Modset Notes

=== Sol

While this repo provides CKAN configs for most of the modifications necessary
to run the Sol planet pack, you still need to do some things yourself. Namely,
this repository does not provide the following:

- Blackrack's Volumetric Clouds v5 (https://www.patreon.com/c/blackrack[Patreon])

== Updating the CKAN packages

There is a link:./rkan/README.adoc[command line tool] to update the CKAN
package set in this repository. The script also holds configurations for which
packages to build.

To run this tool, run `cargo run -- generate`.

You will need to set the `GITHUB_TOKEN` environment variable to a GitHub
Personal Access Token in order to have RKAN generate the relevant metadata
files for your mods. You only need to create a read-only public token here, no
additional scopes are needed when using fine-grained access tokens for this.

On Windows, to set these environment variables, do:

[source,pwsh]
----
$env:GITHUB_TOKEN = "<github pat here>"
----

On Linux and macOS:

[source,bash]
----
export GITHUB_TOKEN="<github pat here>"
----

Then, you can run:

[source,bash]
----
$ cd rkan

# generate all .ckan files, processing 4 mods in parallel
$ cargo run -- generate --jobs 4

# generate specifically Sol-configs
$ cargo run -- generate Sol-Configs
----

== License

This repository (and the configs within it) is licensed under the
file:./LICENSE[Apache 2.0 License]. However, the mods this repository provides
`.ckan` packages for have their own licenses, and you should check those
licenses separately from this repository.