identifier = "Sol-Visuals"
name = "Sol Visuals"
abstract = "EVE & Scatterer configs for Sol"
tags = ["config", "planet-pack"]
license = "restricted"
authors = ["ballisticfox", "Charon_S"]
ksp_version = "1.12"
provides = ["EnvironmentalVisualEnhancements-Config", "EnvironmentalVisualEnhancements-Config-sol", "Scatterer-config", "Scatterer-sunflare"]
repo = "RSS-Reborn/Sol-Visuals"
asset_match = "Sol_Visuals-.*\\.zip"

[resources]
manual = "https://github.com/RSS-Reborn/Sol-Configs/wiki"
homepage = "https://github.com/RSS-Reborn/Sol-Configs/wiki"

[[install]]
file = "GameData/Sol-Visuals"
install_to = "GameData"

[dependencies]
ModuleManager = "*"
Sol-Core = "*"
EnvironmentalVisualEnhancements = "*"
Scatterer = "*"
