identifier = "Sol-Configs"
name = "Sol Configs"
abstract = "The next generation of RSS-Reborn"
tags = ["config", "planet-pack"]
license = "restricted"
authors = ["ballisticfox", "Charon_S"]
ksp_version = "1.12"
repo = "RSS-Reborn/Sol-Configs"
asset_match = "Sol_Configs-.*\\.zip"

[resources]
manual = "/wiki"
homepage = "/wiki"

[[install]]
file = "GameData/Sol-Configs"
install_to = "GameData"

[dependencies]
ModuleManager = "*"
Sol-Core = "*"