identifier = "Sol-Launchsites"
name = "Sol Launchsites Textures"
tags = ["config", "planet-pack"]
license = "restricted"
authors = ["ballisticfox", "Charon_S"]
ksp_version = "1.12"
repo = "RSS-Reborn/Sol-Launchsites"

[resources]
manual = "https://github.com/RSS-Reborn/Sol-Configs/wiki"
homepage = "https://github.com/RSS-Reborn/Sol-Configs/wiki"

[[install]]
file = "GameData/Sol-Textures"
install_to = "GameData"

[dependencies]
Sol-Core = "*"

[[variants]]
identifier = "256x"
name = "256x"
asset_match = "Launchsites-256x.zip"

[[variants]]
identifier = "512x"
name = "512x"
asset_match = "Launchsites-512x.zip"

[[variants]]
identifier = "1024x"
name = "1024x"
asset_match = "Launchsites-1024x.zip"
