identifier = "Sol-UKRadar"
name = "[Sol] UK Radar Sites"
tags = ["config"]
license = "Apache-2.0"
authors = ["hbjydev"]
ksp_version = "1.12"
repo = "hbjydev/UKRadar"

[resources]

[[install]]
file = "GameData/UKRadar"
install_to = "GameData"

[dependencies]
Sol-Core = "*"